title: Producto
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:

        content:
            ordering@: 1

            fields:
                
              header.title:
                ordering@: 0

              header.product_id:
                type: text
                label: 'ID Producto (SKU)'
                data-default@: '\Grav\Plugin\LiliPlugin::generateRandomSku'
                help: 'Lo requiere el sistema de snipcart para identificar el producto'


                
              header.price_mxn:
                ordering@: 2
                type: text
                label: Precio en Pesos (MXN)
              

                
              header.oferta:
                ordering@: 3
                type: toggle
                label: Oferta
                highlight: 1
                default: 0
                options:
                    0: 'No'
                    1: 'Si'
                
              header.temporada:
                ordering@: 4
                type: toggle
                label: Temporada
                highlight: 1
                default: 0
                options:
                    0: 'No'
                    1: 'Si'
                
              header.solo_en_linea:
                ordering@: 5
                type: toggle
                label: Solo en Línea
                highlight: 1
                default: 0
                options:
                    0: 'No'
                    1: 'Si'

              variantes:
                ordering@: 6
                type: section
                title: Variantes
                underline: true

              header.variantes:
                ordering@: 7
                type: list
                label: Variantes
                fields:
                  .talla:
                    type: text
                    label: Talla
                    help: Seleccionar la talla
                  .cantidad:
                    type: text
                    label: Cantidad
                    help: Cantidad en Inventario
                    

                
              header.media_order:
                ordering@: title
              content:
                ordering@: variantes
                classes: corto
             
              

                
              envios:
                type: section
                title: Envíos
                underline: true

              header.envios.peso:
                type: text
                label: Peso (Gramos)
                default: 1000
                help: Escribir el peso del producto en gramos, es para el calculo del costo del envio.


        
        ingles:
            type: tab
            title: Ingles
            ordering@: content
            fields:
              header.title_en:
                type: text
                label: Titulo Ingles
              header.desc_en:
                type: editor
                label: Descripción Ingles


        options:
            ordering@: ingles
        advanced:
            ordering@: options
            unset@: true



